### ISSUE TITLE
Support for long term statistics / new Energy panel

### ISSUE THREAD

**Issue by TravisWilder** [KoljaWindeler/kaco#4]
**Is your feature request related to a problem? Please describe.**
Any of sensors provided with this integrations support long term statistics for use with the new Energy panel in HA.

**Describe the solution you'd like**
HA suggest a solution in: https://www.home-assistant.io/more-info/statistics/

**Comment by kcinnaySte** [comment]
Solved in: #5

**Comment by rfpronk** [comment]
This issue can be closed btw
